spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/ai_lingdaima_user?useSSL=false&serverTimezone=UTC
    username: root
    password: root
  redis:
    host: localhost
    port: 6379
  cache:
    type: caffeine

caffeine:
  spec: maximumSize=1000,expireAfterAccess=5m

dubbo:
  application:
    name: user-service
  registry:
    address: nacos://127.0.0.1:8848
  protocol:
    name: tri
    port: -1

nacos:
  discovery:
    username: nacos
    password: nacos

security:
  oauth2:
    resourceserver:
      jwt:
        issuer-uri: http://localhost:8081/auth/realms/ai
